# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspace

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspace

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/CMakeFiles /workspace//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named r1scoviy

# Build rule for target.
r1scoviy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r1scoviy
.PHONY : r1scoviy

# fast build rule for target.
r1scoviy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/build
.PHONY : r1scoviy/fast

#=============================================================================
# Target rules for targets named QuillLogHelper

# Build rule for target.
QuillLogHelper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QuillLogHelper
.PHONY : QuillLogHelper

# fast build rule for target.
QuillLogHelper/fast:
	$(MAKE) $(MAKESILENT) -f src/LogHelper/CMakeFiles/QuillLogHelper.dir/build.make src/LogHelper/CMakeFiles/QuillLogHelper.dir/build
.PHONY : QuillLogHelper/fast

#=============================================================================
# Target rules for targets named quill

# Build rule for target.
quill: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quill
.PHONY : quill

# fast build rule for target.
quill/fast:
	$(MAKE) $(MAKESILENT) -f _deps/quill-build/CMakeFiles/quill.dir/build.make _deps/quill-build/CMakeFiles/quill.dir/build
.PHONY : quill/fast

src/Simulator/Memory/Memory.o: src/Simulator/Memory/Memory.cpp.o
.PHONY : src/Simulator/Memory/Memory.o

# target to build an object file
src/Simulator/Memory/Memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/Memory/Memory.cpp.o
.PHONY : src/Simulator/Memory/Memory.cpp.o

src/Simulator/Memory/Memory.i: src/Simulator/Memory/Memory.cpp.i
.PHONY : src/Simulator/Memory/Memory.i

# target to preprocess a source file
src/Simulator/Memory/Memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/Memory/Memory.cpp.i
.PHONY : src/Simulator/Memory/Memory.cpp.i

src/Simulator/Memory/Memory.s: src/Simulator/Memory/Memory.cpp.s
.PHONY : src/Simulator/Memory/Memory.s

# target to generate assembly for a file
src/Simulator/Memory/Memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/Memory/Memory.cpp.s
.PHONY : src/Simulator/Memory/Memory.cpp.s

src/Simulator/SPU/Executor/Executor.o: src/Simulator/SPU/Executor/Executor.cpp.o
.PHONY : src/Simulator/SPU/Executor/Executor.o

# target to build an object file
src/Simulator/SPU/Executor/Executor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/Executor/Executor.cpp.o
.PHONY : src/Simulator/SPU/Executor/Executor.cpp.o

src/Simulator/SPU/Executor/Executor.i: src/Simulator/SPU/Executor/Executor.cpp.i
.PHONY : src/Simulator/SPU/Executor/Executor.i

# target to preprocess a source file
src/Simulator/SPU/Executor/Executor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/Executor/Executor.cpp.i
.PHONY : src/Simulator/SPU/Executor/Executor.cpp.i

src/Simulator/SPU/Executor/Executor.s: src/Simulator/SPU/Executor/Executor.cpp.s
.PHONY : src/Simulator/SPU/Executor/Executor.s

# target to generate assembly for a file
src/Simulator/SPU/Executor/Executor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/Executor/Executor.cpp.s
.PHONY : src/Simulator/SPU/Executor/Executor.cpp.s

src/Simulator/SPU/Executor/InstructionDispatcher.o: src/Simulator/SPU/Executor/InstructionDispatcher.cpp.o
.PHONY : src/Simulator/SPU/Executor/InstructionDispatcher.o

# target to build an object file
src/Simulator/SPU/Executor/InstructionDispatcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/Executor/InstructionDispatcher.cpp.o
.PHONY : src/Simulator/SPU/Executor/InstructionDispatcher.cpp.o

src/Simulator/SPU/Executor/InstructionDispatcher.i: src/Simulator/SPU/Executor/InstructionDispatcher.cpp.i
.PHONY : src/Simulator/SPU/Executor/InstructionDispatcher.i

# target to preprocess a source file
src/Simulator/SPU/Executor/InstructionDispatcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/Executor/InstructionDispatcher.cpp.i
.PHONY : src/Simulator/SPU/Executor/InstructionDispatcher.cpp.i

src/Simulator/SPU/Executor/InstructionDispatcher.s: src/Simulator/SPU/Executor/InstructionDispatcher.cpp.s
.PHONY : src/Simulator/SPU/Executor/InstructionDispatcher.s

# target to generate assembly for a file
src/Simulator/SPU/Executor/InstructionDispatcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/Executor/InstructionDispatcher.cpp.s
.PHONY : src/Simulator/SPU/Executor/InstructionDispatcher.cpp.s

src/Simulator/SPU/Fetcher/Fetcher.o: src/Simulator/SPU/Fetcher/Fetcher.cpp.o
.PHONY : src/Simulator/SPU/Fetcher/Fetcher.o

# target to build an object file
src/Simulator/SPU/Fetcher/Fetcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/Fetcher/Fetcher.cpp.o
.PHONY : src/Simulator/SPU/Fetcher/Fetcher.cpp.o

src/Simulator/SPU/Fetcher/Fetcher.i: src/Simulator/SPU/Fetcher/Fetcher.cpp.i
.PHONY : src/Simulator/SPU/Fetcher/Fetcher.i

# target to preprocess a source file
src/Simulator/SPU/Fetcher/Fetcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/Fetcher/Fetcher.cpp.i
.PHONY : src/Simulator/SPU/Fetcher/Fetcher.cpp.i

src/Simulator/SPU/Fetcher/Fetcher.s: src/Simulator/SPU/Fetcher/Fetcher.cpp.s
.PHONY : src/Simulator/SPU/Fetcher/Fetcher.s

# target to generate assembly for a file
src/Simulator/SPU/Fetcher/Fetcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/Fetcher/Fetcher.cpp.s
.PHONY : src/Simulator/SPU/Fetcher/Fetcher.cpp.s

src/Simulator/SPU/ISA/Extension.o: src/Simulator/SPU/ISA/Extension.cpp.o
.PHONY : src/Simulator/SPU/ISA/Extension.o

# target to build an object file
src/Simulator/SPU/ISA/Extension.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/ISA/Extension.cpp.o
.PHONY : src/Simulator/SPU/ISA/Extension.cpp.o

src/Simulator/SPU/ISA/Extension.i: src/Simulator/SPU/ISA/Extension.cpp.i
.PHONY : src/Simulator/SPU/ISA/Extension.i

# target to preprocess a source file
src/Simulator/SPU/ISA/Extension.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/ISA/Extension.cpp.i
.PHONY : src/Simulator/SPU/ISA/Extension.cpp.i

src/Simulator/SPU/ISA/Extension.s: src/Simulator/SPU/ISA/Extension.cpp.s
.PHONY : src/Simulator/SPU/ISA/Extension.s

# target to generate assembly for a file
src/Simulator/SPU/ISA/Extension.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/ISA/Extension.cpp.s
.PHONY : src/Simulator/SPU/ISA/Extension.cpp.s

src/Simulator/SPU/ISA/ExtensionRegistry.o: src/Simulator/SPU/ISA/ExtensionRegistry.cpp.o
.PHONY : src/Simulator/SPU/ISA/ExtensionRegistry.o

# target to build an object file
src/Simulator/SPU/ISA/ExtensionRegistry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/ISA/ExtensionRegistry.cpp.o
.PHONY : src/Simulator/SPU/ISA/ExtensionRegistry.cpp.o

src/Simulator/SPU/ISA/ExtensionRegistry.i: src/Simulator/SPU/ISA/ExtensionRegistry.cpp.i
.PHONY : src/Simulator/SPU/ISA/ExtensionRegistry.i

# target to preprocess a source file
src/Simulator/SPU/ISA/ExtensionRegistry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/ISA/ExtensionRegistry.cpp.i
.PHONY : src/Simulator/SPU/ISA/ExtensionRegistry.cpp.i

src/Simulator/SPU/ISA/ExtensionRegistry.s: src/Simulator/SPU/ISA/ExtensionRegistry.cpp.s
.PHONY : src/Simulator/SPU/ISA/ExtensionRegistry.s

# target to generate assembly for a file
src/Simulator/SPU/ISA/ExtensionRegistry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/ISA/ExtensionRegistry.cpp.s
.PHONY : src/Simulator/SPU/ISA/ExtensionRegistry.cpp.s

src/Simulator/SPU/ISA/InstructionRegistry.o: src/Simulator/SPU/ISA/InstructionRegistry.cpp.o
.PHONY : src/Simulator/SPU/ISA/InstructionRegistry.o

# target to build an object file
src/Simulator/SPU/ISA/InstructionRegistry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/ISA/InstructionRegistry.cpp.o
.PHONY : src/Simulator/SPU/ISA/InstructionRegistry.cpp.o

src/Simulator/SPU/ISA/InstructionRegistry.i: src/Simulator/SPU/ISA/InstructionRegistry.cpp.i
.PHONY : src/Simulator/SPU/ISA/InstructionRegistry.i

# target to preprocess a source file
src/Simulator/SPU/ISA/InstructionRegistry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/ISA/InstructionRegistry.cpp.i
.PHONY : src/Simulator/SPU/ISA/InstructionRegistry.cpp.i

src/Simulator/SPU/ISA/InstructionRegistry.s: src/Simulator/SPU/ISA/InstructionRegistry.cpp.s
.PHONY : src/Simulator/SPU/ISA/InstructionRegistry.s

# target to generate assembly for a file
src/Simulator/SPU/ISA/InstructionRegistry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/ISA/InstructionRegistry.cpp.s
.PHONY : src/Simulator/SPU/ISA/InstructionRegistry.cpp.s

src/Simulator/SPU/ISA/RV32I.o: src/Simulator/SPU/ISA/RV32I.cpp.o
.PHONY : src/Simulator/SPU/ISA/RV32I.o

# target to build an object file
src/Simulator/SPU/ISA/RV32I.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/ISA/RV32I.cpp.o
.PHONY : src/Simulator/SPU/ISA/RV32I.cpp.o

src/Simulator/SPU/ISA/RV32I.i: src/Simulator/SPU/ISA/RV32I.cpp.i
.PHONY : src/Simulator/SPU/ISA/RV32I.i

# target to preprocess a source file
src/Simulator/SPU/ISA/RV32I.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/ISA/RV32I.cpp.i
.PHONY : src/Simulator/SPU/ISA/RV32I.cpp.i

src/Simulator/SPU/ISA/RV32I.s: src/Simulator/SPU/ISA/RV32I.cpp.s
.PHONY : src/Simulator/SPU/ISA/RV32I.s

# target to generate assembly for a file
src/Simulator/SPU/ISA/RV32I.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/ISA/RV32I.cpp.s
.PHONY : src/Simulator/SPU/ISA/RV32I.cpp.s

src/Simulator/SPU/RegisterFile/RegisterFile.o: src/Simulator/SPU/RegisterFile/RegisterFile.cpp.o
.PHONY : src/Simulator/SPU/RegisterFile/RegisterFile.o

# target to build an object file
src/Simulator/SPU/RegisterFile/RegisterFile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/RegisterFile/RegisterFile.cpp.o
.PHONY : src/Simulator/SPU/RegisterFile/RegisterFile.cpp.o

src/Simulator/SPU/RegisterFile/RegisterFile.i: src/Simulator/SPU/RegisterFile/RegisterFile.cpp.i
.PHONY : src/Simulator/SPU/RegisterFile/RegisterFile.i

# target to preprocess a source file
src/Simulator/SPU/RegisterFile/RegisterFile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/RegisterFile/RegisterFile.cpp.i
.PHONY : src/Simulator/SPU/RegisterFile/RegisterFile.cpp.i

src/Simulator/SPU/RegisterFile/RegisterFile.s: src/Simulator/SPU/RegisterFile/RegisterFile.cpp.s
.PHONY : src/Simulator/SPU/RegisterFile/RegisterFile.s

# target to generate assembly for a file
src/Simulator/SPU/RegisterFile/RegisterFile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/RegisterFile/RegisterFile.cpp.s
.PHONY : src/Simulator/SPU/RegisterFile/RegisterFile.cpp.s

src/Simulator/SPU/SPU.o: src/Simulator/SPU/SPU.cpp.o
.PHONY : src/Simulator/SPU/SPU.o

# target to build an object file
src/Simulator/SPU/SPU.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/SPU.cpp.o
.PHONY : src/Simulator/SPU/SPU.cpp.o

src/Simulator/SPU/SPU.i: src/Simulator/SPU/SPU.cpp.i
.PHONY : src/Simulator/SPU/SPU.i

# target to preprocess a source file
src/Simulator/SPU/SPU.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/SPU.cpp.i
.PHONY : src/Simulator/SPU/SPU.cpp.i

src/Simulator/SPU/SPU.s: src/Simulator/SPU/SPU.cpp.s
.PHONY : src/Simulator/SPU/SPU.s

# target to generate assembly for a file
src/Simulator/SPU/SPU.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/SPU/SPU.cpp.s
.PHONY : src/Simulator/SPU/SPU.cpp.s

src/Simulator/Simulator.o: src/Simulator/Simulator.cpp.o
.PHONY : src/Simulator/Simulator.o

# target to build an object file
src/Simulator/Simulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/Simulator.cpp.o
.PHONY : src/Simulator/Simulator.cpp.o

src/Simulator/Simulator.i: src/Simulator/Simulator.cpp.i
.PHONY : src/Simulator/Simulator.i

# target to preprocess a source file
src/Simulator/Simulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/Simulator.cpp.i
.PHONY : src/Simulator/Simulator.cpp.i

src/Simulator/Simulator.s: src/Simulator/Simulator.cpp.s
.PHONY : src/Simulator/Simulator.s

# target to generate assembly for a file
src/Simulator/Simulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/Simulator/Simulator.cpp.s
.PHONY : src/Simulator/Simulator.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r1scoviy.dir/build.make CMakeFiles/r1scoviy.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... QuillLogHelper"
	@echo "... quill"
	@echo "... r1scoviy"
	@echo "... src/Simulator/Memory/Memory.o"
	@echo "... src/Simulator/Memory/Memory.i"
	@echo "... src/Simulator/Memory/Memory.s"
	@echo "... src/Simulator/SPU/Executor/Executor.o"
	@echo "... src/Simulator/SPU/Executor/Executor.i"
	@echo "... src/Simulator/SPU/Executor/Executor.s"
	@echo "... src/Simulator/SPU/Executor/InstructionDispatcher.o"
	@echo "... src/Simulator/SPU/Executor/InstructionDispatcher.i"
	@echo "... src/Simulator/SPU/Executor/InstructionDispatcher.s"
	@echo "... src/Simulator/SPU/Fetcher/Fetcher.o"
	@echo "... src/Simulator/SPU/Fetcher/Fetcher.i"
	@echo "... src/Simulator/SPU/Fetcher/Fetcher.s"
	@echo "... src/Simulator/SPU/ISA/Extension.o"
	@echo "... src/Simulator/SPU/ISA/Extension.i"
	@echo "... src/Simulator/SPU/ISA/Extension.s"
	@echo "... src/Simulator/SPU/ISA/ExtensionRegistry.o"
	@echo "... src/Simulator/SPU/ISA/ExtensionRegistry.i"
	@echo "... src/Simulator/SPU/ISA/ExtensionRegistry.s"
	@echo "... src/Simulator/SPU/ISA/InstructionRegistry.o"
	@echo "... src/Simulator/SPU/ISA/InstructionRegistry.i"
	@echo "... src/Simulator/SPU/ISA/InstructionRegistry.s"
	@echo "... src/Simulator/SPU/ISA/RV32I.o"
	@echo "... src/Simulator/SPU/ISA/RV32I.i"
	@echo "... src/Simulator/SPU/ISA/RV32I.s"
	@echo "... src/Simulator/SPU/RegisterFile/RegisterFile.o"
	@echo "... src/Simulator/SPU/RegisterFile/RegisterFile.i"
	@echo "... src/Simulator/SPU/RegisterFile/RegisterFile.s"
	@echo "... src/Simulator/SPU/SPU.o"
	@echo "... src/Simulator/SPU/SPU.i"
	@echo "... src/Simulator/SPU/SPU.s"
	@echo "... src/Simulator/Simulator.o"
	@echo "... src/Simulator/Simulator.i"
	@echo "... src/Simulator/Simulator.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

